# Generated by Django 5.0.4 on 2024-04-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('nomeLoboratorio', models.CharField(max_length=1000)),
                ('local', models.CharField(max_length=4000)),
                ('descricao', models.CharField(max_length=4000)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
