# Generated by Django 5.0.4 on 2024-04-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxusapp', '0002_laboratoriodisponibilidade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaboratorioDisponibilidade',
        ),
        migrations.AlterField(
            model_name='laboratorios',
            name='descricao',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorios',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='laboratorios',
            name='local',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorios',
            name='nomeLaboratorio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
