# Generated by Django 5.0.4 on 2024-04-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxusapp', '0003_delete_laboratoriodisponibilidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratorioDisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSemana', models.IntegerField(blank=True, default=None, null=True)),
                ('horaInicio', models.TimeField(blank=True, null=True)),
                ('horaTermino', models.TimeField(blank=True, null=True)),
                ('laboratorios', models.ManyToManyField(to='noxusapp.laboratorios')),
            ],
        ),
    ]
