# Generated by Django 5.0.4 on 2024-04-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxusapp', '0005_alter_laboratoriodisponibilidade_diasemana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCategoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='laboratorios',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
