# Generated by Django 5.0.4 on 2024-04-28 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxusapp', '0006_categorias_laboratorios_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorios',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noxusapp.categorias'),
        ),
    ]
