# Generated by Django 5.0.4 on 2024-04-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxusapp', '0007_alter_laboratorios_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('icone', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
    ]
