# Generated by Django 5.0.4 on 2024-05-05 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxusapp', '0010_remove_laboratoriodisponibilidade_laboratorios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailnotificao', models.EmailField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='laboratorios',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noxusapp.categorias'),
        ),
    ]
