# Generated by Django 5.0.4 on 2024-05-06 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noxusapp', '0013_alter_configuracao_portal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracao',
            old_name='portal',
            new_name='porta',
        ),
    ]
