# Generated by Django 5.0.4 on 2024-05-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxusapp', '0014_rename_portal_configuracao_porta'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='host',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
