# Generated by Django 5.0.4 on 2024-05-07 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxusapp', '0015_configuracao_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratorioAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSemana', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('horaInicio', models.TimeField(blank=True, null=True)),
                ('horaTermino', models.TimeField(blank=True, null=True)),
                ('laboratorios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noxusapp.laboratorios')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
