# Generated by Django 5.0.4 on 2024-05-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxusapp', '0016_laboratorioagendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorioagendamento',
            name='diaSemana',
        ),
        migrations.RemoveField(
            model_name='laboratorioagendamento',
            name='horaInicio',
        ),
        migrations.RemoveField(
            model_name='laboratorioagendamento',
            name='horaTermino',
        ),
        migrations.AddField(
            model_name='laboratorioagendamento',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
