# Generated by Django 5.0.4 on 2024-05-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxusapp', '0017_remove_laboratorioagendamento_diasemana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorioagendamento',
            name='horaInicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratorioagendamento',
            name='horaTermino',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
