# Generated by Django 5.0.4 on 2024-05-10 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('noxusapp', '0018_laboratorioagendamento_horainicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
    ]
